{% set name = "libparsifal" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/cca-babel

requirements:
  build:
    - gcc

  run:
    - libgcc
    - libgfortran

build:
  number: 0
  script_env:
    - JAVA_HOME
