language: generic
os:
- linux
- osx
env:
  global:
  - THIS_PACKAGE=libparsifal
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: tar+oUV7sDRNNS2u209T1GoATtzeUDtJ9/i9SOt3y9PsasscV7Xf2eL6Xd5kmMNafZ++IqojIZcmloHrcO6esGyxDUqiHsKPSnY8ktVuHlXmtqbNYOpFiPBeSTYFMng5EHyj+A9oISuZh8vJpP7RIOeVyJv81wQyZlnOkmJxgxOYTI/V0KOiDmYC7P9Zj7H2PbSIbWyhtsvknJCjr/i06Wpb39kwKih3pzm9yAUyVNz8Ti54yrelAgeQwS5vjFwzRBi8lQiaJR/QXrbhaTnc5B4vqh3P86hzgfQdhLRMCofvikfDRw2uz3ca44gGvmInHfnli5wn4qGtBNJVOXOSkzAFsdi2p4uNDTRPOrJEcKR2H/Ulaj0lsBKImofLOqe7qDeSkfrFoXPt4WEPDRUQ4jrrPBxjNt/k8fyoqAT1ApBew9yEWjALRaAWn/fCN4LU3x2ZaJs67xhMvEW14lh6MT6IK531POwCUir84tbYfEdPhPG3SSwQqM0TbjH/zKWdRcPXK420YWOxsVmG57IfnIVXaGzUZ4XRQCOYFtNwzohGRuZJ8EkMQuSpyDywsMbaYqOola2+fUqefsSt4c7f+/byX+Xe/QrppnpQ8rWO+88y10QaxNr8UoPmjBppyAUhun+5B386lQiGu1NtiDN4kARwk2AMO1HyH3QvRI8ESKU=
sudo: false
install:
- bash ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
script:
- conda build recipe -c conda-forge
after_success:
- if [[ $TRAVIS_BRANCH == "master" ]]; then export CHANNEL="main"; fi
- bash ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
